apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "home-assistant.fullname" . }}
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: {{ include "home-assistant.fullname" . }}-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistance.size }}

